### ISSUE TITLE
Versatility Stat Stick does not appear in trinket comparison 

### ISSUE THREAD

**Issue by FoundaBug** [Bloodmallet/bloodytrinkets#21]
When trying to compare trinkets on my feral druid, i was unable to see the option for "Stat Stick (Versatility).

Presuming this is a bug or some other issue?

Regards

**Comment by Bloodmallet** [comment]
Hey thank you for the heads up, sadly I couldn't start generating the necessary data for the comparison tool for 7.3.2 yet and I start doubting, that I can continue the comparison tool for the time beeing. It takes more than 24 hours of calculation time on my computer to generate the data. I'l lthink about some fixes to that, but for the time beeing that page is outdated and shouldn't be used.

A note about your actual question: yes it seems that the last time I generated the data, I missed adding a vers stat stick to the calculation. The normal charts have that problem fixed, so I hope the charts help you in the meantime.
